
server:
    port: 9001
dubbo:
    application:
        name: dubbo_provider0
    protocol:
        name: dubbo
        host: 192.168.1.67
        port: 20883
    registry:
        address: zookeeper://127.0.0.1:2181
