
server:
  port: 9002
dubbo:
  application:
    name: consumer1
    host: 192.168.1.67
  registry:
    address: zookeeper://127.0.0.1:2181
#    scan: com.trus.dubbo_consumer
  consumer:
    check: false
